---
- name: ensure certificates
  hosts: kubernetes:gitlab:localhost
  gather_facts: false
  vars_files:
    - certs/vars.yml
  tasks:
    - import_tasks: certs/ensure_ca.yml
  tags: certificates

- name: Create certificates
  hosts: gitlab
  vars_files:
    - certs/vars.yml
  tasks:
    - name: generate gitlab certificates
      include_tasks: certs/certificate.yml
      with_items:
        - common_name: "{{ gitlab__domain }}"
          subject_alt_name:
            - "IP:{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
            - "DNS:{{ gitlab__domain }}"
  tags: certificates

- name: install gitlab
  hosts: gitlab
  tasks:
    - include_tasks: tasks/gitlab/certificates.yml
    - include_tasks: tasks/gitlab/install.yml
  tags: gitlab
  handlers:
    - import_tasks: "{{ playbook_dir }}/handlers/main.yml"
  
- name: prepare k8s hosts
  hosts: kubernetes
  tasks:
    - include_tasks: tasks/kubernetes/k8s_prepare.yml
    - include_tasks: tasks/kubernetes/install_containerd.yml
    - include_tasks: tasks/kubernetes/k8s_binaries.yml
  tags: k8s_prepare
  handlers:
    - import_tasks: "{{ playbook_dir }}/handlers/main.yml"

- name: setup master nodes
  hosts: masternodes
  tasks:
    - include_tasks: tasks/kubernetes/k8s_config.yml
    - include_tasks: tasks/kubernetes/k8s_high_availability.yml
  tags: k8s_ha
  handlers:
    - import_tasks: "{{ playbook_dir }}/handlers/main.yml"
