---
- name: prepare
  hosts: adminclient
  tasks:
    - name: create config directory
      file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
    - name: unarchive admin.conf
      unarchive:
        src: "modules/07_clusterinit/k8s_config.tgz"
        dest: "{{ ansible_user_dir }}/.kube"
        owner: vagrant
        group: vagrant
        include: 
          - admin.conf
    - name: rename admin.conf
      copy:
        src: "{{ ansible_user_dir }}/.kube/admin.conf"
        dest: "{{ ansible_user_dir }}/.kube/config"
        owner: vagrant
        group: vagrant
        mode: 0700
        remote_src: true
