---
- name: move kubernetes files
  hosts: all
  tasks:
    - name: find kubernetes config files
      become: true
      register: files
      find:
        paths:
          - /etc/kubernetes/pki/etcd
          - /etc/kubernetes/pki
          - /etc/kubernetes/
        patterns:
          - "admin.conf"
          - "ca.*"
          - "front-proxy-ca.*"
          - "sa.*"
        recurse: true
      run_once: true
      delegate_to: masternode

    - name: archive config
      become: true
      archive:
        path: "{{ files.files  | map(attribute='path') | unique  }}"
        dest: "/etc/kubernetes/k8s_config.tgz"
      run_once: true

    - name: fetch archive from master one
      fetch:
        src: /etc/kubernetes/k8s_config.tgz
        dest: "{{ playbook_dir }}/k8s_config.tgz"
        flat: true

- name: template canal
  hosts: all
  tasks:
    - name: template
      template:
        src: templates/kubernetes/canal.yaml
        dest: "{{ ansible_user_dir }}"
      run_once: true

#- name: move kubernetes files
#  hosts: all
#  tasks:
#    - name: unarchive config
#      become: true
#      unarchive:
#        src: "k8s_config.tgz"
#        dest: "/etc/kubernetes/"
