all:
  vars:
    scenario: kubernetes
    ansible_user: vagrant
  children:
    kubernetes:
      children:
        masternodes:
          hosts:
            masternode:
              ipv4address: 192.168.1.11
        workernodes:
          hosts:
            workerone:
              ipv4address: 192.168.1.12
    gitlab:
      hosts:
        gitlab-server:
    adminclient:
      hosts:
        hostone:
