---
all_registry__project_dir: "{{ ansible_user_dir }}/registry"
all_registry__domain: "registry.local"
all_registry__skip_images: false

docker_daemon_json_path: "templates/docker_registry/daemon.json"

container_images:
  - 'k8s.gcr.io/kube-apiserver:v{{ all_kubernetes__k8s_version }}'
  - 'k8s.gcr.io/kube-controller-manager:v{{ all_kubernetes__k8s_version }}'
  - 'k8s.gcr.io/kube-scheduler:v{{ all_kubernetes__k8s_version }}'
  - 'k8s.gcr.io/kube-proxy:v{{ all_kubernetes__k8s_version }}'
  - 'k8s.gcr.io/pause:{{ all_kubernetes__pause_version }}'
  - 'k8s.gcr.io/etcd:{{ all_kubernetes__etcd_version }}'
  - 'k8s.gcr.io/coredns/coredns:v{{ all_kubernetes__coredns_version }}'
  - 'busybox:1.30'
  - 'calico/node:v3.21.2'
  - 'calico/pod2daemon-flexvol:v3.21.2'
  - 'calico/cni:v3.21.2'
  - 'quay.io/coreos/flannel:v0.13.0'
  - 'calico/kube-controllers:v3.21.2'
  - 'kubernetesui/dashboard:v2.0.0'
  - 'kubernetesui/metrics-scraper:v1.0.4'
  - 'weaveworks/weave-kube:2.8.1'
  - 'weaveworks/weave-npc:2.8.1'