---
- name: set apt key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: setup repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com focal main
    filename: hashicorp
    state: present
  become: true

- name: setup pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true
