---
- name: "Install required packages on Ubuntu"
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - tar
    - apt-transport-https
    - libseccomp2
    - util-linux
    - curl

- name: Disable swapoff
  become: true
  command: swapoff -a
  changed_when: false

- name: Disable swapoff permanently
  become: true
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: true

- name: ensure br_netfilter kernel module is loaded
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: check if br_netfilter kernel module is loaded
  register: result
  become: true
  shell: set -o pipefail | cat /proc/modules | grep -c br_netfilter
  failed_when: result.stdout is search('0')
  changed_when: false

- name: make bridged traffic visible to iptables
  become: true
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
  with_items:
    - name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
    - name: net.bridge.bridge-nf-call-iptables
      value: '1'
    - name: net.ipv4.ip_forward
      value: 1
