---
- name: install containerd
  hosts: kubernetes
  vars:
    containerd_release_version: 1.6.2
    cni_bin_dir: /opt/cni/bin/
    cni_conf_dir: /etc/cni/net.d/
  handlers:
    - name: restart containerd
      become: true
      systemd:
        name: containerd
        daemon_reload: true
        state: restarted
        enabled: true

  tasks:
    - name: Install containerd requirements
      become: true
      package:
        name: "{{ item }}"
        state: latest
      with_items:
          - unzip
          - tar
          - apt-transport-https
          - btrfs-progs
          - libseccomp2
          - util-linux

    - name: "Get Containerd"
      become: true
      unarchive:
        src: "https://github.com/containerd/containerd/releases/download/v{{ containerd_release_version }}/cri-containerd-cni-{{ containerd_release_version }}-linux-amd64.tar.gz"
        dest: "/"
        remote_src: yes

    - name: "Create a directory for cni binary"
      become: true
      file: path={{ cni_bin_dir }} state=directory

    - name: "Create a directory for cni config files"
      become: true
      file: path={{ cni_conf_dir }} state=directory

    - name: "Create a directory for containerd config"
      become: true
      file: path=/etc/containerd state=directory

    - name: Create directories for containerd config
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: 0555
      loop:
        - "/etc/containerd"
        - "/etc/containerd/certs.d"
        - "/etc/containerd/certs.d/{{ all_all__docker_registry }}"

    - name: create config for containerd
      become: true
      template:
        src: templates/config.toml.j2
        dest: /etc/containerd/config.toml
        mode: 0644
      notify:
        - restart containerd

    - name: template config
      become: true
      template:
        src: templates/hosts.toml.j2
        dest: "/etc/containerd/certs.d/{{ all_all__docker_registry }}/hosts.toml"
        mode: 0644

    - name: copy ca crt to containerd
      become: true
      copy:
        src: certs/ca.crt
        dest: "/etc/containerd/certs.d/{{ all_all__docker_registry }}"
        mode: 0644

    - name: Start Containerd
      become: true
      systemd:
        name: containerd
        daemon_reload: true
        state: started
        enabled: true
