---
- name: install containerd
  hosts: kubernetes
  handlers:
    - name: restart containerd
      become: true
      systemd:
        name: containerd
        daemon_reload: true
        state: restarted
        enabled: true

  tasks:
    - name: install containerd
      become: true
      apt:
        pkg:
          - containerd

    - name: set containerd binary on hold
      become: true
      dpkg_selections:
        name: "containerd"
        selection: hold

    - name: Create directories for containerd config
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: 0555
      loop:
        - "/etc/containerd"
        - "/etc/containerd/certs.d"
        - "/etc/containerd/certs.d/{{ all_all__docker_registry }}"

    - name: create config for containerd
      become: true
      template:
        src: templates/config.toml.j2
        dest: /etc/containerd/config.toml
        mode: 0644
      notify:
        - restart containerd

    - name: template config
      become: true
      template:
        src: templates/hosts.toml.j2
        dest: "/etc/containerd/certs.d/{{ all_all__docker_registry }}/hosts.toml"
        mode: 0644

    - name: copy ca crt to containerd
      become: true
      copy:
        src: certs/ca.crt
        dest: "/etc/containerd/certs.d/{{ all_all__docker_registry }}"
        mode: 0644

    - name: Start Containerd
      become: true
      systemd:
        name: containerd
        daemon_reload: true
        state: started
        enabled: true
